kind: Namespace
apiVersion: v1
metadata:
  name: eqj-web-ns
  labels:
    name: eqj-web-ns
---

apiVersion: v1
kind: Service
metadata:
  name: eqj-lb-svc
  namespace: eqj-web-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: eqj-web
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eqj-web-deployment
  namespace: eqj-web-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eqj-web
  template:
    metadata:
      labels:
        app: eqj-web
    spec:
      containers:
      - name: eqj-nginx
        image: equablejarl/eks-nginx
        ports:
        - containerPort: 80